/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthButton: typeof import('./../src/views/auth/components/AuthButton.vue')['default']
    Components: typeof import('./../src/views/components/Components.vue')['default']
    Compute: typeof import('./../src/components/Compute.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FF: typeof import('./../src/components/FF.vue')['default']
    Header: typeof import('./../src/components/Header.vue')['default']
    IconArrowLeft: typeof import('~icons/icon/arrow-left')['default']
    IconArrowRight: typeof import('~icons/icon/arrow-right')['default']
    IconCar: typeof import('~icons/icon/car')['default']
    IconCart: typeof import('~icons/icon/cart')['default']
    IconColor: typeof import('~icons/icon/color')['default']
    IconComponents: typeof import('~icons/icon/components')['default']
    IconIcons: typeof import('~icons/icon/icons')['default']
    IconTypography: typeof import('~icons/icon/typography')['default']
    Navigation: typeof import('./../src/components/Navigation.vue')['default']
    NavigationIcons: typeof import('./../src/components/NavigationIcons.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./../src/components/SectionHeader.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
